apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: httpapi-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: httpapi-role
subjects:
  - kind: ServiceAccount
    name: controller-httpapi
    namespace: system
