# permissions for end users to view osbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osbuild-viewer-role
rules:
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuilds/status
  verbs:
  - get
