// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package restapi

// MessageResponse defines model for message-response.
type MessageResponse struct {
	// Content
	Content   *interface{} `json:"content,omitempty"`
	Directive *string      `json:"directive,omitempty"`
	MessageId *string      `json:"message_id,omitempty"`
}
