apiVersion: osbuilder.project-flotta.io/v1alpha1
kind: OSBuildConfig
metadata:
  name: osbuildconfig-sample
spec:
  details:
    distribution: rhel-86
    customizations:
      packages:
        - node_exporter
        - ansible
    targetImage:
      architecture: x86_64
      targetImageType: edge-container
      osTree:
        url: "https://hostedimagesserver.flotta.io/"
        ref: "rhel/8/x86_64/edge"
  template:
    osBuildConfigTemplateRef: osbuildconfigtemplate-sample
    parameters:
      - name: foo
        value: bar
  triggers:
    configChange: true
    webHook:
      secretReference:
        # Run separately `oc create secret generic mysecret --from-literal=WebHookSecretKey=secretvalue1 -n osbuild`
        name: mysecret
      allowEnv: true


