apiVersion: osbuilder.project-flotta.io/v1alpha1
kind: OSBuild
metadata:
  name: osbuild-sample
spec:
  details:
    distribution: rhel-86
    customizations:
      packages:
        - node_exporter
        - ansible
    targetImage:
      architecture: x86_64
      targetImageType: edge-container
      osTree:
        url: "https://hostedimagesserver.flotta.io/"
        ref: "rhel/8/x86_64/edge"
  triggeredBy: "UpdateCR"